pool:
  vmImage: 'VS2017-Win2016'

steps:
- powershell: |
    $buildNumber = [int]$Env:BUILD_ID
    write-host "Build number $buildNumber" -fore white
    $basePath = resolve-path .
    $keyPath = "$basePath\key.snk"
    $sign = $false
    if ($Env:KEY_DATA)
    {
        $keyData = [System.Convert]::FromBase64String($Env:KEY_DATA)
        [System.IO.File]::WriteAllBytes($keyPath, $keyData)
        $sign = $true
    }
    write-host "Sign assemblies $sign" -fore white
    $formattedBuildNumber = $buildNumber.ToString("D6")
    $nugetPrerelease = "build$formattedBuildNumber"
    .\Build\runbuild.ps1 -properties @{"signAssemblies"=$sign; "signKeyPath"=$keyPath; "treatWarningsAsErrors"=$true; "nugetPrerelease"=$nugetPrerelease;}
  env:
    KEY_DATA: $(newtonsoft.keyData)
    BUILD_ID: $(Build.BuildId)
  displayName: 'Run build'

- task: PublishTestResults@2
  inputs:
    testRunner: 'NUnit'
    testResultsFiles: '**/Working/*.xml'
  displayName: 'Publish NUnit results'

- task: PublishTestResults@2
  inputs:
    testRunner: 'VSTest'
    testResultsFiles: '**/Working/*.trx'
  displayName: 'Publish dotnet test results'

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'json-net'
    packagesToPush: '**/Working/*.nupkg'
  displayName: 'Publish NuGet package'
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))