pool:
  vmImage: 'VS2017-Win2016'

steps:
- powershell: |
    #Write-Host "BUILD_SOURCESDIRECTORY contents:"
    #gci $Env:BUILD_SOURCESDIRECTORY
    #Write-Host "Over and out."
    .\Build\runbuild.ps1
  env:
    KEY_DATA: $(KEY_DATA)
  displayName: 'Run build'

- task: PublishTestResults@2
  inputs:
    testRunner: 'XUnit'
    testResultsFiles: '**/Working/*.xml'

- task: PublishTestResults@2
  inputs:
    testRunner: 'VSTest'
    testResultsFiles: '**/Working/*.trx'
